title: Typeinthetalkies
description: A website about typography in movies
footer_text: Copyright 2021 Lauren Pine
header_feature_image: ../uploads/type-in-the-talkies-2-.jpg
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
