title: Typeinthetalkies
description: A website about typography in movies
footer_text: Copyright 2021 Lauren Pine
header_feature_image: ../uploads/banner-image-2.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/type-blog-logo.png
favicon: ../uploads/type-blog-logo.png
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - name: About Me
    siteurl: /aboutme/
    tab: true
